export enum ExchangeCurrencyType {
  MONEY = "MONEY",
  CANDY = "CANDY",
  VOUCHER_REGULAR = "VOUCHER_REGULAR",
  VOUCHER_PLUS = "VOUCHER_PLUS",
  VOUCHER_PREMIUM = "VOUCHER_PREMIUM",
  VOUCHER_GOLD = "VOUCHER_GOLD",
}