export enum ZMoveEffect {
  ATTACK_UP_1_WHEN_Z,
  ATTACK_UP_2_WHEN_Z,
  ATTACK_UP_3_WHEN_Z,
  DEFENSE_UP_1_WHEN_Z,
  SP_ATTACK_UP_1_WHEN_Z,
  SP_DEFENSE_UP_1_WHEN_Z,
  SPEED_UP_1_WHEN_Z,
  ACCURACY_UP_1_WHEN_Z,
  EVASION_UP_1_WHEN_Z,
  ALL_STATS_UP_1_WHEN_Z,
  CRITICAL_UP_2_WHEN_Z,
  CLEAR_STAT_DROPS,
  FULL_HP_RECOVERY,
  FOLLOW_ME_STATE,
  CUSTOM_FUNCTION, // 예외 처리용
}
